Memo/models.py
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from sqlalchemy.orm import relationship
db = SQLAlchemy() # Flaskのappと未連携の状態で空インスタンスを生成

class Memo(db.Model):
	__tablename__ = 'memos'
	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	title = db.Column(db.String(50), nullable=False)
	content = db.Column(db.Text) # 文字数無制限
 	# MemoのUser_idカラムはUserモデルのidカラムを外部キーとして設定
	user_id = db.Column(db.Integer, db.ForeignKey('users.id', name='fk_momos_users'), nullable=False) # 必ず紐付くことを保証
	# MemoモデルはUserとリレーションシップを定義するためUserモデルのmemosを指定
	user = relationship('User', back_populates='memos')

class User(UserMixin, db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(50), unique=True, nullable=False)
	password = db.Column(db.String(120), nullable=False)
  # UserモデルはMemoとリレーションシップを定義するためMemoモデルのuserを指定
	memos = relationship('Memo', back_populates='user')

	# ハッシュ化したパスワードを上記のカラムに保持
	def set_password(self, password):
		self.password = generate_password_hash(password)
	# 保持したハッシュパスワードと渡された平文のパスワードと認証し真偽値を返す
	def check_password(self, password):
		return check_password_hash(self.password, password)

Memo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, ValidationError
from models import Memo, User
class MemoForm(FlaskForm):
    title = StringField(
        "タイトル：",
        validators=[
            DataRequired("タイトルは必須入力です"),
            Length(max=10, message="10文字以下で入力してください"),
        ],
    )
    content = TextAreaField("内容：")
    submit = SubmitField("保存")

    def validate_title(self, title):
        memo = Memo.query.filter_by(title=title.data).first()
        if memo:
            raise ValidationError(
                f"タイトル「{title.data}」は既に存在します。別のタイトルを入力してください。"
            )

class LoginForm(FlaskForm):
	username = StringField('ユーザ名：', validators=[DataRequired('ユーザ名は必須入力です。')])
	password = PasswordField('パスワード：', validators=[Length(4, 10, 'パスワードの長さは4文字以上10文字以内です')])
	submit = SubmitField('ログイン')
	# カスタムバリデータとして英数記号が含まれていなければraiseで例外を明示的に発生させる
	def validate_password(self, password):
		if not (any(c.isalpha() for c in password.data) and \
		any(c.isdigit() for c in password.data) and \
		any(c in '!@#$%^&*()' for c in password.data)):
		  raise ValidationError('パスワードには【英数字と記号：!@#$%^&*()】を含める必要があります。')

class SignUpForm(LoginForm): # ログイン処理と同じなため機能を継承
	submit = SubmitField('サインアップ') # ボタンラベルをオーバーライド
	# ユーザ名の重複判定のみ追加
	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user:
			raise ValidationError('そのユーザ名はすでに使用されれています')

class WikiForm(FlaskForm):
  keyword = StringField('検索ワード：', render_kw={'placeholder':'入力してください'})
  submit = SubmitField('Wiki検索')

Memo/app.py
from flask import Flask
from flask_migrate import Migrate
from models import db, User
from flask_login import LoginManager
from auth.views import auth_bp
from memo.views import memo_bp
from wiki.views import wiki_bp

app = Flask(__name__)

# 設定ファイルからConfigクラスを読み込み
app.config.from_object('config.Config')

# SQLAlchemyとFlaskAppの連携
db.init_app(app)
# Flask(App)とSQLAlchemy(DB)とマイグレーションの連携
migrate = Migrate(app, db)
login_manager = LoginManager()
login_manager.init_app(app) # Flaskアプリに紐付け
# アクセス制限ページからリダイレクト後のflashメッセージ
login_manager.login_message = '認証していません：ログインしてください'
login_manager.login_view = 'auth.login' # 不正アクセスはログインページへ
# Blueprintをアプリに紐付け
app.register_blueprint(auth_bp)
app.register_blueprint(memo_bp)
app.register_blueprint(wiki_bp)

@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))

# CRUD+404(Views:routing→Template)の展開
from views import * # noqa: F403 E402

if __name__ == '__main__':
	app.run()

Memo/memo/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models import db, Memo
from forms import MemoForm
from flask_login import login_required, current_user

memo_bp = Blueprint('memo', __name__, url_prefix='/memo')

@memo_bp.route('/')
@login_required
def index():
	memos = Memo.query.filter_by(user_id=current_user.id).all() # メモ全件取得
	return render_template('memo/index.j2', memos=memos)

@memo_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
  form = MemoForm()
  if form.validate_on_submit():
    title = form.title.data
    content = form.content.data
    memo = Memo(title=title, content=content, user_id=current_user.id)
    db.session.add(memo)
    db.session.commit()
    flash('登録しました')
    return redirect(url_for('memo.index'))
  return render_template('memo/create_form.j2', form=form)

@memo_bp.route('/update/<int:memo_id>', methods=['GET', 'POST'])
@login_required
def update(memo_id):
  target_data = Memo.query.filter_by(id=memo_id, user_id=current_user.id).first_or_404() # 見つからない場合は404エラー
  form = MemoForm(obj=target_data)
  if request.method == 'POST' and form.validate():
    target_data.title = form.title.data
    target_data.content = form.content.data
    db.session.commit()
    flash('変更しました')
    return redirect(url_for('memo.index'))
  return render_template('memo/update_form.j2', form=form, edit_id=target_data.id) # 1件分をフォームに渡す

@memo_bp.route('/delete/<int:memo_id>')
@login_required
def delete(memo_id):
  memo = Memo.query.filter_by(id=memo_id, user_id=current_user.id).first_or_404()
  db.session.delete(memo)
  db.session.commit()
  flash('変更しました')
  return redirect(url_for('memo.index'))

@memo_bp.route('create_from_search', methods=['POSt'])
@login_required
def create_from_search():
	title = request.form['title']
	content = request.form['content']
	new_memo = Memo(title=title, content=content, user_id=current_user.id)
	db.session.add(new_memo)
	db.session.commit()
	flash('Wikiからデータ登録しました')
	return redirect(url_for('memo.index'))

@memo_bp.route('/show/<int:memo_id>')
@login_required
def show(memo_id):
  target_data = Memo.query.filter_by(id=memo_id, user_id=current_user.id).first_or_404() # 見つからない場合は404エラー
  return render_template('memo/show.j2', show=target_data)

Memo/views.py
from flask import render_template
from app import app
from werkzeug.exceptions import NotFound # エラー画面用モジュールの追加

@app.errorhandler(NotFound) # 404のNotFoundエラーが起きた際に実行
def show_404_page(error):
	msg = error.description # エラーメッセージを取得
	print(f'エラー内容：{msg}')
	return render_template('errors/404.j2', msg=msg), 404

Memo/wiki/views.py
from flask import render_template, Blueprint
from wikipediaapi import Wikipedia
from forms import WikiForm
from flask_login import login_required

wiki_bp = Blueprint('wiki', __name__, url_prefix='/wiki')
wiki_ja = Wikipedia('ja') # 日本語Wikiのインスタンスを取得

@wiki_bp.route('/search', methods=['GET', 'POST'])
@login_required
def search():
	form = WikiForm()
	if form.validate_on_submit():
		keyword = form.keyword.data
		page = wiki_ja.page(keyword) # Wiki内検索
		if page.exists(): # 検索ページがあれば
			# 記事の要約文の最初の200文字文と、そのページのURLを絶対パスで取得
			return render_template('wiki/wiki_search_result.j2', \
			keyword=keyword, summary=page.summary[:200], url=page.fullurl)
		else:
			return render_template('wiki/wiki_search_result.j2', error='指定されたキーワードの結果は見つかりませんでした。')
	return render_template('wiki/wiki_search.j2', form=form) 

Memo/templates/_formhelpers.j2
{% macro render_field(field) %}
  <dt>{{ field.label }}</dt>
  <dd>
    {{ field(**kwargs) | safe }}
  </dd>
  {% if field.errors %}
    <ul>
      {% for error in field.errors %}<li>{{ error }}</li>{% endfor %}
    </ul>
  {% endif %}
{% endmacro %}

Memo/templates/base.j2
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>メモアプリ</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="icon" href="images/favicon.png" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  </head>
  <body>
    <div class="container">
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('auth.logout') }}">ログアウト</a>
        {% endif %}
        <p><a href="{{ url_for('wiki.search') }}">Wikipediaの検索へ</a></p>
        {% block content %}
        {% endblock content %}
        {% for message in get_flashed_messages() %}
            <div>{{ message }}</div>
        {% endfor %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

Memo/templates/memo/create_form.j2
{% extends "base.j2" %}
{% block content %}
  <h1>新しいメモを作成</h1>
  {% from '_formhelpers.j2' import render_field %}
  <form action="{{ url_for('memo.create') }}" method="post" novalidate>
    {{ form.hidden_tag() }}
    {{ render_field(form.title) }}
    {{ render_field(form.content, rows=5, cols=50) }}
    {{ form.submit }}
  </form>
  <p><a href="{{ url_for('memo.index') }}">一覧ページへ戻る</a></p>
{% endblock content %}

Memo/templates/memo/index.j2
{% extends "base.j2" %}
{% block content %}
  <h1>メモ一覧</h1>
  <ul>
    {% for memo in memos %}
      <li>
        <a href="{{ url_for('memo.show', memo_id=memo.id) }}">{{ memo.title }}</a> :
        <a href="{{ url_for('memo.update', memo_id=memo.id) }}">編集</a> |
        <a href="{{ url_for('memo.delete', memo_id=memo.id) }}">削除</a>
      </li>
    {% endfor %}
  </ul>
  <p><a href="{{ url_for('memo.create') }}">新しいメモを作成</a></p>
{% endblock content %}

Memo/templates/memo/show.j2
{% extends "base.j2" %}
{% block content %}
  <h1>メモ詳細</h1>
  <h2>{{ show.title }}</h2>
  <p>{{ show.content }}</p>
  <p><a href="{{ url_for('memo.index') }}">一覧ページに戻る</a></p>
{% endblock content %}

Memo/templates/memo/update_form.j2
{% extends "base.j2" %}
{% block content %}
  <h1>メモを編集</h1>
  {% from '_formhelpers.j2' import render_field %}
  <form action="{{ url_for('memo.update', memo_id=edit_id) }}"
        method="post"
        novalidate>
    {{ form.hidden_tag() }}
    {{ render_field(form.title) }}
    {{ render_field(form.content, row=5, cols=50) }}
    {{ form.submit }}
  </form>
  <p><a href="{{ url_for('memo.index') }}">一覧ページへ戻る</a></p>
{% endblock content %}

Memo/templates/wiki/wiki_search.j2
{% extends "base.j2" %}
{% block content %}
  <h1>Wikipediaの検索</h1>
  {% from '_formhelpers.j2' import render_field %}
  <form action="{{ url_for('wiki.search') }}" method="post" novalidate>
    {{ form.hidden_tag() }}
    {{ render_field(form.keyword) }}
    {{ form.submit }}
  </form>
  <p>
    <a href="{{ url_for('memo.index') }}">一覧ページへ戻る</a>
  </p>
{% endblock content %}

Memo/templates/wiki/wiki_search_result.j2
{% extends "base.j2" %}
{% block content %}
  {% if error %}
    <h2>{{ error }}</h2>
  {% else: %}
    <h2>検索情報： 「{{ keyword }}」</h2>
    <p>{{ summary }}...<a href="{{ url }}" target="_blank">もっと見る</a></p>
  {% endif %}
  <form action="{{ url_for('memo.create_from_search') }}" method="post" novalidate>
		<input type="hidden" name="title" value="{{ keyword }}">
		<input type="hidden" name="content" value="{{ summary }}">
		<input type="submit" value="メモに追加">
	</form>
  <p>
    <a href="{{ url_for('memo.index') }}">一覧ページへ戻る</a>
  </p>
{% endblock content %}